export const VALIDATION_TYPES = {
    LABOR: 'LABOR',
    PARTS: 'PARTS',
    OPERATIONS: 'OPERATIONS',
    PHOTOS: 'PHOTOS',
    VEHICLE: 'VEHICLE'
};

export const NOTIFICATION_TYPES = {
    INFO: 'INFO',
    WARNING: 'WARNING',
    ERROR: 'ERROR',
    AI_UPDATE: 'AI_UPDATE',
    RULE_UPDATE: 'RULE_UPDATE'
};

export const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTH_ERROR: 'AUTH_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    SERVER_ERROR: 'SERVER_ERROR'
}; 