name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and Export
      run: |
        npm run build
        npm run export
      env:
        NEXT_PUBLIC_BASE_PATH: /resynciq-compliance-engine

    - name: Verify root index.html
      run: |
        if [ ! -f "out/index.html" ]; then
          echo "Error: index.html not found in root directory"
          exit 1
        fi
        echo "Root index.html verified"

    - name: Add .nojekyll file
      run: touch out/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out 