name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and Export
      run: npm run deploy
      env:
        NEXT_PUBLIC_APP_URL: https://resetroot99.github.io/resynciq-compliance-engine
        NEXT_PUBLIC_BASE_PATH: /resynciq-compliance-engine

    - name: Add .nojekyll file
      run: touch out/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        cname: app.resynciq.com # Optional: If you have a custom domain 