name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and Export
      run: |
        npm run build
        npm run export
      env:
        NEXT_PUBLIC_BASE_PATH: /resynciq-compliance-engine

    - name: Verify file structure
      run: |
        ls -R out
        echo "Verifying file paths..."
        find out -type f | grep -i 'index.html'
        find out -type f | grep -i '404.html'

    - name: Add .nojekyll file
      run: touch out/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out 